// Comprehensive list of course categories across all fields

export interface CategoryGroup {
  name: string;
  categories: string[];
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    name: 'Technology & IT',
    categories: [
      'Web Development',
      'Mobile App Development',
      'Software Engineering',
      'Data Science',
      'Machine Learning',
      'Artificial Intelligence',
      'Cloud Computing',
      'Cybersecurity',
      'DevOps',
      'Blockchain',
      'Game Development',
      'Database Management',
      'DBMS',
      'Networking',
      'IT Support',
      'Programming Languages',
    ],
  },
  {
    name: 'Business & Management',
    categories: [
      'Business Administration',
      'Project Management',
      'Entrepreneurship',
      'Leadership',
      'Strategic Management',
      'Operations Management',
      'Supply Chain Management',
      'Risk Management',
      'Business Analytics',
      'E-commerce',
      'Startups',
      'Business Strategy',
    ],
  },
  {
    name: 'Marketing & Sales',
    categories: [
      'Digital Marketing',
      'Social Media Marketing',
      'Content Marketing',
      'SEO & SEM',
      'Email Marketing',
      'Brand Management',
      'Sales',
      'Advertising',
      'Public Relations',
      'Market Research',
      'Copywriting',
      'Affiliate Marketing',
    ],
  },
  {
    name: 'Finance & Accounting',
    categories: [
      'Accounting',
      'Financial Analysis',
      'Investment',
      'Stock Trading',
      'Cryptocurrency',
      'Banking',
      'Taxation',
      'Financial Planning',
      'Corporate Finance',
      'Bookkeeping',
      'Auditing',
      'Insurance',
    ],
  },
  {
    name: 'Design & Creative',
    categories: [
      'Graphic Design',
      'UI/UX Design',
      'Web Design',
      'Interior Design',
      'Fashion Design',
      'Industrial Design',
      'Animation',
      'Video Production',
      'Photography',
      '3D Modeling',
      'Motion Graphics',
      'Illustration',
      'Logo Design',
      'Brand Identity',
    ],
  },
  {
    name: 'Human Resources',
    categories: [
      'HR Management',
      'Recruitment & Hiring',
      'Employee Training',
      'Performance Management',
      'Compensation & Benefits',
      'Labor Law',
      'Organizational Development',
      'Talent Management',
      'Employee Relations',
      'HR Analytics',
      'Diversity & Inclusion',
    ],
  },
  {
    name: 'Health & Medical',
    categories: [
      'Healthcare Administration',
      'Nursing',
      'Medical Coding',
      'Pharmacy',
      'Mental Health',
      'Nutrition & Dietetics',
      'Public Health',
      'First Aid & CPR',
      'Medical Terminology',
      'Health Informatics',
      'Fitness & Exercise',
      'Yoga & Meditation',
    ],
  },
  {
    name: 'Education & Teaching',
    categories: [
      'Teaching Methods',
      'Curriculum Development',
      'Educational Technology',
      'Online Teaching',
      'Special Education',
      'Early Childhood Education',
      'Higher Education',
      'Corporate Training',
      'Tutoring',
      'Instructional Design',
    ],
  },
  {
    name: 'Personal Development',
    categories: [
      'Communication Skills',
      'Public Speaking',
      'Time Management',
      'Productivity',
      'Critical Thinking',
      'Problem Solving',
      'Emotional Intelligence',
      'Confidence Building',
      'Goal Setting',
      'Memory & Study Skills',
      'Negotiation',
      'Career Development',
    ],
  },
  {
    name: 'Languages',
    categories: [
      'English',
      'Spanish',
      'French',
      'German',
      'Chinese (Mandarin)',
      'Japanese',
      'Arabic',
      'Korean',
      'Italian',
      'Portuguese',
      'Russian',
      'Urdu',
      'Hindi',
    ],
  },
  {
    name: 'Engineering',
    categories: [
      'Mechanical Engineering',
      'Electrical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Aerospace Engineering',
      'Biomedical Engineering',
      'Environmental Engineering',
      'Robotics',
      'AutoCAD & Drafting',
      'Electronics',
    ],
  },
  {
    name: 'Law & Legal',
    categories: [
      'Contract Law',
      'Corporate Law',
      'Criminal Law',
      'Intellectual Property',
      'Employment Law',
      'Real Estate Law',
      'International Law',
      'Legal Writing',
      'Compliance',
      'Paralegal Studies',
    ],
  },
  {
    name: 'Science & Research',
    categories: [
      'Biology',
      'Chemistry',
      'Physics',
      'Mathematics',
      'Statistics',
      'Environmental Science',
      'Astronomy',
      'Research Methods',
      'Lab Techniques',
      'Scientific Writing',
    ],
  },
  {
    name: 'Arts & Humanities',
    categories: [
      'Music',
      'Fine Arts',
      'Creative Writing',
      'Literature',
      'History',
      'Philosophy',
      'Psychology',
      'Sociology',
      'Anthropology',
      'Film Studies',
      'Theater & Acting',
    ],
  },
  {
    name: 'Lifestyle & Hobbies',
    categories: [
      'Cooking & Culinary',
      'Baking & Pastry',
      'Gardening',
      'Pet Care',
      'Travel Planning',
      'Home Improvement',
      'Crafts & DIY',
      'Music Production',
      'Sports & Athletics',
      'Gaming',
    ],
  },
  {
    name: 'Government & Public Sector',
    categories: [
      'Public Administration',
      'Policy Making',
      'Urban Planning',
      'Social Work',
      'Nonprofit Management',
      'Community Development',
      'Grant Writing',
      'Government Relations',
    ],
  },
];

// Flatten all categories into a single array
export const ALL_CATEGORIES: string[] = CATEGORY_GROUPS.flatMap(group => group.categories);

// Get category with its group name
export const getCategoryWithGroup = (category: string): string | null => {
  for (const group of CATEGORY_GROUPS) {
    if (group.categories.includes(category)) {
      return group.name;
    }
  }
  return null;
};
