# Generated by Django 5.2.4 on 2025-08-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
    ]
