# Generated by Django 5.2.4 on 2025-08-12 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_content_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
