# Generated by Django 5.2.4 on 2025-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_coursemodule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
