# Generated by Django 5.2.4 on 2025-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_content_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('qa', 'Q&A')], default='qa', max_length=5),
        ),
    ]
