# Generated by Django 5.2.4 on 2025-08-31 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_assignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('qa', 'Q&A')], max_length=5)),
                ('text', models.TextField()),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.assignment')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('assignment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.assignmentquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
