# Generated by Django 5.2.4 on 2025-08-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assignmentsubmission_answers_assignmentquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
