# Generated by Django 5.2.4 on 2025-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_assignmentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
