# Generated by Django 5.2.4 on 2025-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_assignmentquestion_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='acceptable_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='required_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
