# Generated by Django 5.2.6 on 2025-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='teacher_reply',
            field=models.TextField(null=True, blank=True),
        ),
    ]
