# Generated by Django 5.2.6 on 2025-09-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_courserating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserating',
            name='teacher_reply',
        ),
    ]
