# Generated by Django 5.2.4 on 2025-10-11 17:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_supportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
