# Generated by Django 5.2.4 on 2025-10-11 17:31

from django.db import migrations

def migrate_local_videos_to_cloudinary(apps, schema_editor):
    """
    One-time migration that uploads existing local video files under MEDIA_ROOT to Cloudinary
    and updates Content.video to the resulting Cloudinary public_id.

    This is safe to re-run: rows with no local file present or already migrated are skipped.
    """
    import os
    from django.conf import settings
    try:
        import cloudinary
        from cloudinary import uploader
    except Exception:
        # If cloudinary isn't available, skip gracefully
        return

    Content = apps.get_model('myapp', 'Content')

    # Read raw values to avoid CloudinaryField interpretation
    rows = Content.objects.exclude(video__isnull=True).values('id', 'video')

    for row in rows:
        cid = row['id']
        video_val = str(row.get('video') or '').strip()
        if not video_val:
            continue
        # If value looks like a URL (already Cloudinary or remote), skip
        if video_val.startswith('http://') or video_val.startswith('https://'):
            continue
        # Build local file path assuming the value is a path relative to MEDIA_ROOT
        # Common case: 'videos/filename.mp4'
        # Also support '/media/videos/..' by stripping prefix
        rel = video_val
        if rel.startswith('/'):
            # Strip leading slash and any 'media/' prefix
            rel = rel.lstrip('/')
            if rel.startswith('media/'):
                rel = rel[len('media/'):]
        local_path = os.path.join(str(settings.MEDIA_ROOT), rel)
        if not os.path.isfile(local_path):
            # No local file found; nothing to migrate for this row
            continue
        try:
            # Upload to Cloudinary as video resource, keep under 'videos' folder for organization
            res = uploader.upload(
                local_path,
                resource_type='video',
                folder='videos',
                use_filename=True,
                unique_filename=False,
                overwrite=False,
                secure=True,
            )
            public_id = res.get('public_id')
            if public_id:
                # Update instance to reference Cloudinary resource
                obj = Content.objects.get(id=cid)
                setattr(obj, 'video', public_id)
                obj.save(update_fields=['video'])
        except Exception:
            # Best-effort migration: skip on errors for individual files
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_content_video'),
    ]

    operations = [
        migrations.RunPython(migrate_local_videos_to_cloudinary, reverse_code=migrations.RunPython.noop)
    ]
