# Generated by Django 4.2.7 on 2026-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_badge_xptransaction_userstats_userbadge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
