# Generated by Django 5.2.4 on 2026-02-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_increase_preferred_category_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("function_calls", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.CharField(blank=True, max_length=20, null=True)),
                ("response_time_ms", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="myapp_chatm_user_id_cba6c9_idx")],
            },
        ),
    ]
