# Generated by Django 5.2.4 on 2026-02-22 02:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_update_chatmessage_source_cerebras'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('file', 'File')], max_length=10),
        ),
    ]
